version: '3.9'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html/
      - type: bind
        source: .
        target: /var/www/html
    ports:
      - 80:80
